---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=2.0.0
  - ANSIBLE_VERSION=latest

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Basic role syntax check
  - "ansible-playbook -i localhost, tests/test.yml --syntax-check"

  # Basic role install
  - "ansible-playbook -i localhost, tests/test.yml --connection=local --sudo"

  # Idempotency check
  - >
    ansible-playbook -i localhost, tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotency: PASS' && exit 0)
    || (echo 'Idempotency: FAIL' && exit 1)

  - >
    [ -f "/usr/local/bin/gocryptfs" ] && echo "Gocryptfs installed" && exit 0 || echo "Gocryptfs not installed" && exit 1

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/