---
# tasks file for ansible-gocryptfs

- name: check gocryptfs file
  stat:
    path: "{{gocryptfs_install_directory}}/{{gocryptfs_name}}"
  register: gocryptfs_executable

- name: get gocryptfs version info
  shell: "{{gocryptfs_install_directory}}/{{gocryptfs_name}} --version"
  register: gocryptfs_version_info
  when: gocryptfs_executable.stat.exists

- name: get latest version info
  uri:
    url: "{{gocryptfs_package_meta_json}}"
    method: GET
    return_content: yes
  register: latest_version_info
  when: gocryptfs_version == "latest"

- name: set latest version as fact
  set_fact:
    gocryptfs_version: "{{ (latest_version_info.content|from_json).tag_name  | replace('v', '')}}"
  when: gocryptfs_version == "latest"

- name: check gocryptfs version
  set_fact:
    desired_version_installed: "{{ gocryptfs_version_info.stdout_lines[0].find(gocryptfs_version) != -1}}"
  when: gocryptfs_executable.stat.exists

- include: "install.yml"
  when: not gocryptfs_executable.stat.exists or not desired_version_installed
